connected_check_task:
  name: Run Android e2e tests
  only_if: $CIRRUS_BRANCH == "deploy" || $CIRRUS_PR != ""
  env:
    API_LEVEL: 28
    TARGET: default
    ARCH: x86_64
    JAVA_TOOL_OPTIONS: -Xmx6g
    ANDROID_EMULATOR_HOME: ${HOME}/.android
    GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
  container:
    image: digidem/docker-android
    kvm: true
    cpu: 8
    memory: 24G
  npm_install_script: |
    mkdir -p nodejs-assets
    npm ci
  build_backend_script: npm run build:backend
  build_translations_script: npm run build:translations
  build_detox_script: npm run build-detox-android
  create_device_script: |
    echo no | avdmanager create avd --force --name emu --abi "${TARGET}/${ARCH}" --device "Nexus 6" --package "system-images;android-${API_LEVEL};${TARGET};${ARCH}"
    echo "Emulator version:"
    $ANDROID_HOME/emulator/emulator @emu -version
    $ANDROID_HOME/emulator/emulator -list-avds
    echo "Hardware acceleration:"
    $ANDROID_HOME/emulator/emulator -accel-check
    echo "\nEmulator config"
    cat $HOME/.android/avd/emu.avd/config.ini
  start_emulator_background_script: $ANDROID_HOME/emulator/emulator -avd emu -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back emulated
  wait_for_emulator_script: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'
  disable_animations_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
  metro_background_script: npm start
  run_tests_script: |
    adb devices
    $ANDROID_HOME/emulator/emulator -list-avds
    ! ls -al $ANDROID_HOME/avd
    ! ls -al ~/.android/avd
    mkdir -p artifacts
    npm run test-detox-android -- --record-videos all --record-logs all
  always:
    test_artifacts:
      path: "artifacts/*"
