// flow-typed signature: 36a622723d736b9c3b46d99bf20dd88b
// flow-typed version: <<STUB>>/appium_v^1.7.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appium'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appium' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appium/bin/ios-webkit-debug-proxy-launcher' {
  declare module.exports: any;
}

declare module 'appium/build/lib/appium' {
  declare module.exports: any;
}

declare module 'appium/build/lib/config' {
  declare module.exports: any;
}

declare module 'appium/build/lib/grid-register' {
  declare module.exports: any;
}

declare module 'appium/build/lib/logger' {
  declare module.exports: any;
}

declare module 'appium/build/lib/logsink' {
  declare module.exports: any;
}

declare module 'appium/build/lib/main' {
  declare module.exports: any;
}

declare module 'appium/build/lib/parser' {
  declare module.exports: any;
}

declare module 'appium/build/lib/utils' {
  declare module.exports: any;
}

declare module 'appium/build/test/config-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/driver-e2e-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/driver-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/helpers' {
  declare module.exports: any;
}

declare module 'appium/build/test/logger-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/parser-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/shrinkwrap-specs' {
  declare module.exports: any;
}

declare module 'appium/build/test/utils-specs' {
  declare module.exports: any;
}

declare module 'appium/gulpfile' {
  declare module.exports: any;
}

declare module 'appium/lib/appium' {
  declare module.exports: any;
}

declare module 'appium/lib/config' {
  declare module.exports: any;
}

declare module 'appium/lib/grid-register' {
  declare module.exports: any;
}

declare module 'appium/lib/logger' {
  declare module.exports: any;
}

declare module 'appium/lib/logsink' {
  declare module.exports: any;
}

declare module 'appium/lib/main' {
  declare module.exports: any;
}

declare module 'appium/lib/parser' {
  declare module.exports: any;
}

declare module 'appium/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appium/bin/ios-webkit-debug-proxy-launcher.js' {
  declare module.exports: $Exports<'appium/bin/ios-webkit-debug-proxy-launcher'>;
}
declare module 'appium/build/lib/appium.js' {
  declare module.exports: $Exports<'appium/build/lib/appium'>;
}
declare module 'appium/build/lib/config.js' {
  declare module.exports: $Exports<'appium/build/lib/config'>;
}
declare module 'appium/build/lib/grid-register.js' {
  declare module.exports: $Exports<'appium/build/lib/grid-register'>;
}
declare module 'appium/build/lib/logger.js' {
  declare module.exports: $Exports<'appium/build/lib/logger'>;
}
declare module 'appium/build/lib/logsink.js' {
  declare module.exports: $Exports<'appium/build/lib/logsink'>;
}
declare module 'appium/build/lib/main.js' {
  declare module.exports: $Exports<'appium/build/lib/main'>;
}
declare module 'appium/build/lib/parser.js' {
  declare module.exports: $Exports<'appium/build/lib/parser'>;
}
declare module 'appium/build/lib/utils.js' {
  declare module.exports: $Exports<'appium/build/lib/utils'>;
}
declare module 'appium/build/test/config-specs.js' {
  declare module.exports: $Exports<'appium/build/test/config-specs'>;
}
declare module 'appium/build/test/driver-e2e-specs.js' {
  declare module.exports: $Exports<'appium/build/test/driver-e2e-specs'>;
}
declare module 'appium/build/test/driver-specs.js' {
  declare module.exports: $Exports<'appium/build/test/driver-specs'>;
}
declare module 'appium/build/test/helpers.js' {
  declare module.exports: $Exports<'appium/build/test/helpers'>;
}
declare module 'appium/build/test/logger-specs.js' {
  declare module.exports: $Exports<'appium/build/test/logger-specs'>;
}
declare module 'appium/build/test/parser-specs.js' {
  declare module.exports: $Exports<'appium/build/test/parser-specs'>;
}
declare module 'appium/build/test/shrinkwrap-specs.js' {
  declare module.exports: $Exports<'appium/build/test/shrinkwrap-specs'>;
}
declare module 'appium/build/test/utils-specs.js' {
  declare module.exports: $Exports<'appium/build/test/utils-specs'>;
}
declare module 'appium/gulpfile.js' {
  declare module.exports: $Exports<'appium/gulpfile'>;
}
declare module 'appium/lib/appium.js' {
  declare module.exports: $Exports<'appium/lib/appium'>;
}
declare module 'appium/lib/config.js' {
  declare module.exports: $Exports<'appium/lib/config'>;
}
declare module 'appium/lib/grid-register.js' {
  declare module.exports: $Exports<'appium/lib/grid-register'>;
}
declare module 'appium/lib/logger.js' {
  declare module.exports: $Exports<'appium/lib/logger'>;
}
declare module 'appium/lib/logsink.js' {
  declare module.exports: $Exports<'appium/lib/logsink'>;
}
declare module 'appium/lib/main.js' {
  declare module.exports: $Exports<'appium/lib/main'>;
}
declare module 'appium/lib/parser.js' {
  declare module.exports: $Exports<'appium/lib/parser'>;
}
declare module 'appium/lib/utils.js' {
  declare module.exports: $Exports<'appium/lib/utils'>;
}
