// flow-typed signature: e494cb7256ec738ad2a0904eb8392210
// flow-typed version: <<STUB>>/backoff-rxjs_v^0.0.9/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backoff-rxjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'backoff-rxjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backoff-rxjs/dist/index' {
  declare module.exports: any;
}

declare module 'backoff-rxjs/dist/observable/intervalBackoff' {
  declare module.exports: any;
}

declare module 'backoff-rxjs/dist/operators/retryBackoff' {
  declare module.exports: any;
}

declare module 'backoff-rxjs/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backoff-rxjs/dist/index.js' {
  declare module.exports: $Exports<'backoff-rxjs/dist/index'>;
}
declare module 'backoff-rxjs/dist/observable/intervalBackoff.js' {
  declare module.exports: $Exports<'backoff-rxjs/dist/observable/intervalBackoff'>;
}
declare module 'backoff-rxjs/dist/operators/retryBackoff.js' {
  declare module.exports: $Exports<'backoff-rxjs/dist/operators/retryBackoff'>;
}
declare module 'backoff-rxjs/dist/utils.js' {
  declare module.exports: $Exports<'backoff-rxjs/dist/utils'>;
}
