// flow-typed signature: 8894d315dd84bd00f96e5adc84d1d6aa
// flow-typed version: <<STUB>>/buble_v^0.19.6/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buble/bin/handleError' {
  declare module.exports: any;
}

declare module 'buble/bin/runBuble' {
  declare module.exports: any;
}

declare module 'buble/bin/showHelp' {
  declare module.exports: any;
}

declare module 'buble/dist/buble-browser-deps.umd' {
  declare module.exports: any;
}

declare module 'buble/dist/buble-browser.cjs' {
  declare module.exports: any;
}

declare module 'buble/dist/buble-browser.es' {
  declare module.exports: any;
}

declare module 'buble/dist/buble.cjs' {
  declare module.exports: any;
}

declare module 'buble/dist/buble.es' {
  declare module.exports: any;
}

declare module 'buble/register' {
  declare module.exports: any;
}

declare module 'buble/src/index' {
  declare module.exports: any;
}

declare module 'buble/src/program/BlockStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/extractNames' {
  declare module.exports: any;
}

declare module 'buble/src/program/keys' {
  declare module.exports: any;
}

declare module 'buble/src/program/Node' {
  declare module.exports: any;
}

declare module 'buble/src/program/Program' {
  declare module.exports: any;
}

declare module 'buble/src/program/Scope' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ArrayExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ArrowFunctionExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/AssignmentExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/AwaitExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/BinaryExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/BreakStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/CallExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ClassBody' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ClassDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ClassExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ContinueStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ExportDefaultDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ExportNamedDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ForInStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ForOfStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ForStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/FunctionDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/FunctionExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/Identifier' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/IfStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/Import' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ImportDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ImportDefaultSpecifier' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ImportSpecifier' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/index' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXAttribute' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXClosingElement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXClosingFragment' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXElement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXExpressionContainer' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXFragment' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXOpeningElement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXOpeningFragment' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/JSXSpreadAttribute' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/Literal' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/MemberExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/NewExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ObjectExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/Property' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ReturnStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/shared/LoopStatement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/shared/ModuleDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/Super' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/TaggedTemplateExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/TemplateElement' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/TemplateLiteral' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/ThisExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/UpdateExpression' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/VariableDeclaration' {
  declare module.exports: any;
}

declare module 'buble/src/program/types/VariableDeclarator' {
  declare module.exports: any;
}

declare module 'buble/src/program/wrap' {
  declare module.exports: any;
}

declare module 'buble/src/support' {
  declare module.exports: any;
}

declare module 'buble/src/utils/array' {
  declare module.exports: any;
}

declare module 'buble/src/utils/checkConst' {
  declare module.exports: any;
}

declare module 'buble/src/utils/CompileError' {
  declare module.exports: any;
}

declare module 'buble/src/utils/deindent' {
  declare module.exports: any;
}

declare module 'buble/src/utils/destructure' {
  declare module.exports: any;
}

declare module 'buble/src/utils/getSnippet' {
  declare module.exports: any;
}

declare module 'buble/src/utils/isReference' {
  declare module.exports: any;
}

declare module 'buble/src/utils/locate' {
  declare module.exports: any;
}

declare module 'buble/src/utils/patterns' {
  declare module.exports: any;
}

declare module 'buble/src/utils/removeTrailingComma' {
  declare module.exports: any;
}

declare module 'buble/src/utils/reserved' {
  declare module.exports: any;
}

declare module 'buble/src/utils/spread' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buble/bin/handleError.js' {
  declare module.exports: $Exports<'buble/bin/handleError'>;
}
declare module 'buble/bin/runBuble.js' {
  declare module.exports: $Exports<'buble/bin/runBuble'>;
}
declare module 'buble/bin/showHelp.js' {
  declare module.exports: $Exports<'buble/bin/showHelp'>;
}
declare module 'buble/dist/buble-browser-deps.umd.js' {
  declare module.exports: $Exports<'buble/dist/buble-browser-deps.umd'>;
}
declare module 'buble/dist/buble-browser.cjs.js' {
  declare module.exports: $Exports<'buble/dist/buble-browser.cjs'>;
}
declare module 'buble/dist/buble-browser.es.js' {
  declare module.exports: $Exports<'buble/dist/buble-browser.es'>;
}
declare module 'buble/dist/buble.cjs.js' {
  declare module.exports: $Exports<'buble/dist/buble.cjs'>;
}
declare module 'buble/dist/buble.es.js' {
  declare module.exports: $Exports<'buble/dist/buble.es'>;
}
declare module 'buble/register.js' {
  declare module.exports: $Exports<'buble/register'>;
}
declare module 'buble/src/index.js' {
  declare module.exports: $Exports<'buble/src/index'>;
}
declare module 'buble/src/program/BlockStatement.js' {
  declare module.exports: $Exports<'buble/src/program/BlockStatement'>;
}
declare module 'buble/src/program/extractNames.js' {
  declare module.exports: $Exports<'buble/src/program/extractNames'>;
}
declare module 'buble/src/program/keys.js' {
  declare module.exports: $Exports<'buble/src/program/keys'>;
}
declare module 'buble/src/program/Node.js' {
  declare module.exports: $Exports<'buble/src/program/Node'>;
}
declare module 'buble/src/program/Program.js' {
  declare module.exports: $Exports<'buble/src/program/Program'>;
}
declare module 'buble/src/program/Scope.js' {
  declare module.exports: $Exports<'buble/src/program/Scope'>;
}
declare module 'buble/src/program/types/ArrayExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/ArrayExpression'>;
}
declare module 'buble/src/program/types/ArrowFunctionExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/ArrowFunctionExpression'>;
}
declare module 'buble/src/program/types/AssignmentExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/AssignmentExpression'>;
}
declare module 'buble/src/program/types/AwaitExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/AwaitExpression'>;
}
declare module 'buble/src/program/types/BinaryExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/BinaryExpression'>;
}
declare module 'buble/src/program/types/BreakStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/BreakStatement'>;
}
declare module 'buble/src/program/types/CallExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/CallExpression'>;
}
declare module 'buble/src/program/types/ClassBody.js' {
  declare module.exports: $Exports<'buble/src/program/types/ClassBody'>;
}
declare module 'buble/src/program/types/ClassDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/ClassDeclaration'>;
}
declare module 'buble/src/program/types/ClassExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/ClassExpression'>;
}
declare module 'buble/src/program/types/ContinueStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/ContinueStatement'>;
}
declare module 'buble/src/program/types/ExportDefaultDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/ExportDefaultDeclaration'>;
}
declare module 'buble/src/program/types/ExportNamedDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/ExportNamedDeclaration'>;
}
declare module 'buble/src/program/types/ForInStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/ForInStatement'>;
}
declare module 'buble/src/program/types/ForOfStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/ForOfStatement'>;
}
declare module 'buble/src/program/types/ForStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/ForStatement'>;
}
declare module 'buble/src/program/types/FunctionDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/FunctionDeclaration'>;
}
declare module 'buble/src/program/types/FunctionExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/FunctionExpression'>;
}
declare module 'buble/src/program/types/Identifier.js' {
  declare module.exports: $Exports<'buble/src/program/types/Identifier'>;
}
declare module 'buble/src/program/types/IfStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/IfStatement'>;
}
declare module 'buble/src/program/types/Import.js' {
  declare module.exports: $Exports<'buble/src/program/types/Import'>;
}
declare module 'buble/src/program/types/ImportDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/ImportDeclaration'>;
}
declare module 'buble/src/program/types/ImportDefaultSpecifier.js' {
  declare module.exports: $Exports<'buble/src/program/types/ImportDefaultSpecifier'>;
}
declare module 'buble/src/program/types/ImportSpecifier.js' {
  declare module.exports: $Exports<'buble/src/program/types/ImportSpecifier'>;
}
declare module 'buble/src/program/types/index.js' {
  declare module.exports: $Exports<'buble/src/program/types/index'>;
}
declare module 'buble/src/program/types/JSXAttribute.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXAttribute'>;
}
declare module 'buble/src/program/types/JSXClosingElement.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXClosingElement'>;
}
declare module 'buble/src/program/types/JSXClosingFragment.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXClosingFragment'>;
}
declare module 'buble/src/program/types/JSXElement.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXElement'>;
}
declare module 'buble/src/program/types/JSXExpressionContainer.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXExpressionContainer'>;
}
declare module 'buble/src/program/types/JSXFragment.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXFragment'>;
}
declare module 'buble/src/program/types/JSXOpeningElement.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXOpeningElement'>;
}
declare module 'buble/src/program/types/JSXOpeningFragment.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXOpeningFragment'>;
}
declare module 'buble/src/program/types/JSXSpreadAttribute.js' {
  declare module.exports: $Exports<'buble/src/program/types/JSXSpreadAttribute'>;
}
declare module 'buble/src/program/types/Literal.js' {
  declare module.exports: $Exports<'buble/src/program/types/Literal'>;
}
declare module 'buble/src/program/types/MemberExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/MemberExpression'>;
}
declare module 'buble/src/program/types/NewExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/NewExpression'>;
}
declare module 'buble/src/program/types/ObjectExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/ObjectExpression'>;
}
declare module 'buble/src/program/types/Property.js' {
  declare module.exports: $Exports<'buble/src/program/types/Property'>;
}
declare module 'buble/src/program/types/ReturnStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/ReturnStatement'>;
}
declare module 'buble/src/program/types/shared/LoopStatement.js' {
  declare module.exports: $Exports<'buble/src/program/types/shared/LoopStatement'>;
}
declare module 'buble/src/program/types/shared/ModuleDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/shared/ModuleDeclaration'>;
}
declare module 'buble/src/program/types/Super.js' {
  declare module.exports: $Exports<'buble/src/program/types/Super'>;
}
declare module 'buble/src/program/types/TaggedTemplateExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/TaggedTemplateExpression'>;
}
declare module 'buble/src/program/types/TemplateElement.js' {
  declare module.exports: $Exports<'buble/src/program/types/TemplateElement'>;
}
declare module 'buble/src/program/types/TemplateLiteral.js' {
  declare module.exports: $Exports<'buble/src/program/types/TemplateLiteral'>;
}
declare module 'buble/src/program/types/ThisExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/ThisExpression'>;
}
declare module 'buble/src/program/types/UpdateExpression.js' {
  declare module.exports: $Exports<'buble/src/program/types/UpdateExpression'>;
}
declare module 'buble/src/program/types/VariableDeclaration.js' {
  declare module.exports: $Exports<'buble/src/program/types/VariableDeclaration'>;
}
declare module 'buble/src/program/types/VariableDeclarator.js' {
  declare module.exports: $Exports<'buble/src/program/types/VariableDeclarator'>;
}
declare module 'buble/src/program/wrap.js' {
  declare module.exports: $Exports<'buble/src/program/wrap'>;
}
declare module 'buble/src/support.js' {
  declare module.exports: $Exports<'buble/src/support'>;
}
declare module 'buble/src/utils/array.js' {
  declare module.exports: $Exports<'buble/src/utils/array'>;
}
declare module 'buble/src/utils/checkConst.js' {
  declare module.exports: $Exports<'buble/src/utils/checkConst'>;
}
declare module 'buble/src/utils/CompileError.js' {
  declare module.exports: $Exports<'buble/src/utils/CompileError'>;
}
declare module 'buble/src/utils/deindent.js' {
  declare module.exports: $Exports<'buble/src/utils/deindent'>;
}
declare module 'buble/src/utils/destructure.js' {
  declare module.exports: $Exports<'buble/src/utils/destructure'>;
}
declare module 'buble/src/utils/getSnippet.js' {
  declare module.exports: $Exports<'buble/src/utils/getSnippet'>;
}
declare module 'buble/src/utils/isReference.js' {
  declare module.exports: $Exports<'buble/src/utils/isReference'>;
}
declare module 'buble/src/utils/locate.js' {
  declare module.exports: $Exports<'buble/src/utils/locate'>;
}
declare module 'buble/src/utils/patterns.js' {
  declare module.exports: $Exports<'buble/src/utils/patterns'>;
}
declare module 'buble/src/utils/removeTrailingComma.js' {
  declare module.exports: $Exports<'buble/src/utils/removeTrailingComma'>;
}
declare module 'buble/src/utils/reserved.js' {
  declare module.exports: $Exports<'buble/src/utils/reserved'>;
}
declare module 'buble/src/utils/spread.js' {
  declare module.exports: $Exports<'buble/src/utils/spread'>;
}
