// flow-typed signature: 4c60581e30d3551f6b6e9e49edeb20ff
// flow-typed version: <<STUB>>/cheap-ruler_v^2.5.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cheap-ruler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "cheap-ruler" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "cheap-ruler/cheap-ruler" {
  declare module.exports: any;
}

declare module "cheap-ruler/cheap-ruler.min" {
  declare module.exports: any;
}

// Filename aliases
declare module "cheap-ruler/cheap-ruler.js" {
  declare module.exports: $Exports<"cheap-ruler/cheap-ruler">;
}
declare module "cheap-ruler/cheap-ruler.min.js" {
  declare module.exports: $Exports<"cheap-ruler/cheap-ruler.min">;
}
declare module "cheap-ruler/index" {
  declare module.exports: $Exports<"cheap-ruler">;
}
declare module "cheap-ruler/index.js" {
  declare module.exports: $Exports<"cheap-ruler">;
}
