// flow-typed signature: c9dd8ec4daa49228351d929cf4f1a602
// flow-typed version: <<STUB>>/docz-plugin-netlify_v^1.1.4/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz-plugin-netlify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz-plugin-netlify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'docz-plugin-netlify/index' {
  declare module.exports: $Exports<'docz-plugin-netlify'>;
}
declare module 'docz-plugin-netlify/index.js' {
  declare module.exports: $Exports<'docz-plugin-netlify'>;
}
