// flow-typed signature: d5407704e2df2bee0315ca8ca830f00f
// flow-typed version: <<STUB>>/expo-linear-gradient_v^8.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "expo-linear-gradient" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "expo-linear-gradient/build" {
  declare module.exports: any;
}

declare module "expo-linear-gradient/build/LinearGradient" {
  declare module.exports: any;
}

declare module "expo-linear-gradient/build/NativeLinearGradient.android" {
  declare module.exports: any;
}

declare module "expo-linear-gradient/build/NativeLinearGradient.ios" {
  declare module.exports: any;
}

declare module "expo-linear-gradient/build/NativeLinearGradient.web" {
  declare module.exports: any;
}

// Filename aliases
declare module "expo-linear-gradient/build/index" {
  declare module.exports: $Exports<"expo-linear-gradient/build">;
}
declare module "expo-linear-gradient/build/index.js" {
  declare module.exports: $Exports<"expo-linear-gradient/build">;
}
declare module "expo-linear-gradient/build/LinearGradient.js" {
  declare module.exports: $Exports<"expo-linear-gradient/build/LinearGradient">;
}
declare module "expo-linear-gradient/build/NativeLinearGradient.android.js" {
  declare module.exports: $Exports<
    "expo-linear-gradient/build/NativeLinearGradient.android"
  >;
}
declare module "expo-linear-gradient/build/NativeLinearGradient.ios.js" {
  declare module.exports: $Exports<
    "expo-linear-gradient/build/NativeLinearGradient.ios"
  >;
}
declare module "expo-linear-gradient/build/NativeLinearGradient.web.js" {
  declare module.exports: $Exports<
    "expo-linear-gradient/build/NativeLinearGradient.web"
  >;
}
