// flow-typed signature: b79769e5e717a678f69f2bf7cced1a19
// flow-typed version: <<STUB>>/expo-sensors_v^8.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-sensors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "expo-sensors" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "expo-sensors/build/Accelerometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/Barometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/DeviceMotion" {
  declare module.exports: any;
}

declare module "expo-sensors/build/DeviceSensor" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExpoBarometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExpoBarometer.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentAccelerometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentAccelerometer.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentDeviceMotion" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentDeviceMotion.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentGyroscope" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentGyroscope.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentMagnetometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentMagnetometer.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentMagnetometerUncalibrated" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentMagnetometerUncalibrated.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentPedometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ExponentPedometer.web" {
  declare module.exports: any;
}

declare module "expo-sensors/build/Gyroscope" {
  declare module.exports: any;
}

declare module "expo-sensors/build" {
  declare module.exports: any;
}

declare module "expo-sensors/build/Magnetometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/MagnetometerUncalibrated" {
  declare module.exports: any;
}

declare module "expo-sensors/build/Pedometer" {
  declare module.exports: any;
}

declare module "expo-sensors/build/ThreeAxisSensor" {
  declare module.exports: any;
}

declare module "expo-sensors/build/utils/isSensorEnabledAsync.web" {
  declare module.exports: any;
}

// Filename aliases
declare module "expo-sensors/build/Accelerometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/Accelerometer">;
}
declare module "expo-sensors/build/Barometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/Barometer">;
}
declare module "expo-sensors/build/DeviceMotion.js" {
  declare module.exports: $Exports<"expo-sensors/build/DeviceMotion">;
}
declare module "expo-sensors/build/DeviceSensor.js" {
  declare module.exports: $Exports<"expo-sensors/build/DeviceSensor">;
}
declare module "expo-sensors/build/ExpoBarometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExpoBarometer">;
}
declare module "expo-sensors/build/ExpoBarometer.web.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExpoBarometer.web">;
}
declare module "expo-sensors/build/ExponentAccelerometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentAccelerometer">;
}
declare module "expo-sensors/build/ExponentAccelerometer.web.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/ExponentAccelerometer.web"
  >;
}
declare module "expo-sensors/build/ExponentDeviceMotion.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentDeviceMotion">;
}
declare module "expo-sensors/build/ExponentDeviceMotion.web.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/ExponentDeviceMotion.web"
  >;
}
declare module "expo-sensors/build/ExponentGyroscope.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentGyroscope">;
}
declare module "expo-sensors/build/ExponentGyroscope.web.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentGyroscope.web">;
}
declare module "expo-sensors/build/ExponentMagnetometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentMagnetometer">;
}
declare module "expo-sensors/build/ExponentMagnetometer.web.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/ExponentMagnetometer.web"
  >;
}
declare module "expo-sensors/build/ExponentMagnetometerUncalibrated.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/ExponentMagnetometerUncalibrated"
  >;
}
declare module "expo-sensors/build/ExponentMagnetometerUncalibrated.web.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/ExponentMagnetometerUncalibrated.web"
  >;
}
declare module "expo-sensors/build/ExponentPedometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentPedometer">;
}
declare module "expo-sensors/build/ExponentPedometer.web.js" {
  declare module.exports: $Exports<"expo-sensors/build/ExponentPedometer.web">;
}
declare module "expo-sensors/build/Gyroscope.js" {
  declare module.exports: $Exports<"expo-sensors/build/Gyroscope">;
}
declare module "expo-sensors/build/index" {
  declare module.exports: $Exports<"expo-sensors/build">;
}
declare module "expo-sensors/build/index.js" {
  declare module.exports: $Exports<"expo-sensors/build">;
}
declare module "expo-sensors/build/Magnetometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/Magnetometer">;
}
declare module "expo-sensors/build/MagnetometerUncalibrated.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/MagnetometerUncalibrated"
  >;
}
declare module "expo-sensors/build/Pedometer.js" {
  declare module.exports: $Exports<"expo-sensors/build/Pedometer">;
}
declare module "expo-sensors/build/ThreeAxisSensor.js" {
  declare module.exports: $Exports<"expo-sensors/build/ThreeAxisSensor">;
}
declare module "expo-sensors/build/utils/isSensorEnabledAsync.web.js" {
  declare module.exports: $Exports<
    "expo-sensors/build/utils/isSensorEnabledAsync.web"
  >;
}
