// flow-typed signature: 47ffc1e81530dcc1f3ab2a04fc5731cd
// flow-typed version: <<STUB>>/expo-camera_v^3.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-camera/build/Camera' {
  declare module.exports: any;
}

declare module 'expo-camera/build/Camera.types' {
  declare module.exports: any;
}

declare module 'expo-camera/build/CameraModule/CameraModule' {
  declare module.exports: any;
}

declare module 'expo-camera/build/CameraModule/CameraModule.types' {
  declare module.exports: any;
}

declare module 'expo-camera/build/CameraModule/CameraUtils' {
  declare module.exports: any;
}

declare module 'expo-camera/build/CameraModule/CapabilityUtils' {
  declare module.exports: any;
}

declare module 'expo-camera/build/CameraModule/constants' {
  declare module.exports: any;
}

declare module 'expo-camera/build/ExponentCamera' {
  declare module.exports: any;
}

declare module 'expo-camera/build/ExponentCamera.web' {
  declare module.exports: any;
}

declare module 'expo-camera/build/ExponentCameraManager' {
  declare module.exports: any;
}

declare module 'expo-camera/build/ExponentCameraManager.web' {
  declare module.exports: any;
}

declare module 'expo-camera/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-camera/build/Camera.js' {
  declare module.exports: $Exports<'expo-camera/build/Camera'>;
}
declare module 'expo-camera/build/Camera.types.js' {
  declare module.exports: $Exports<'expo-camera/build/Camera.types'>;
}
declare module 'expo-camera/build/CameraModule/CameraModule.js' {
  declare module.exports: $Exports<'expo-camera/build/CameraModule/CameraModule'>;
}
declare module 'expo-camera/build/CameraModule/CameraModule.types.js' {
  declare module.exports: $Exports<'expo-camera/build/CameraModule/CameraModule.types'>;
}
declare module 'expo-camera/build/CameraModule/CameraUtils.js' {
  declare module.exports: $Exports<'expo-camera/build/CameraModule/CameraUtils'>;
}
declare module 'expo-camera/build/CameraModule/CapabilityUtils.js' {
  declare module.exports: $Exports<'expo-camera/build/CameraModule/CapabilityUtils'>;
}
declare module 'expo-camera/build/CameraModule/constants.js' {
  declare module.exports: $Exports<'expo-camera/build/CameraModule/constants'>;
}
declare module 'expo-camera/build/ExponentCamera.js' {
  declare module.exports: $Exports<'expo-camera/build/ExponentCamera'>;
}
declare module 'expo-camera/build/ExponentCamera.web.js' {
  declare module.exports: $Exports<'expo-camera/build/ExponentCamera.web'>;
}
declare module 'expo-camera/build/ExponentCameraManager.js' {
  declare module.exports: $Exports<'expo-camera/build/ExponentCameraManager'>;
}
declare module 'expo-camera/build/ExponentCameraManager.web.js' {
  declare module.exports: $Exports<'expo-camera/build/ExponentCameraManager.web'>;
}
declare module 'expo-camera/build/index.js' {
  declare module.exports: $Exports<'expo-camera/build/index'>;
}
