// flow-typed signature: eb85aaff697c566f87efc0bf7759f12e
// flow-typed version: <<STUB>>/expo-location_v^8.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-location'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "expo-location" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "expo-location/build/ExpoLocation" {
  declare module.exports: any;
}

declare module "expo-location/build/ExpoLocation.web" {
  declare module.exports: any;
}

declare module "expo-location/build/Location" {
  declare module.exports: any;
}

// Filename aliases
declare module "expo-location/build/ExpoLocation.js" {
  declare module.exports: $Exports<"expo-location/build/ExpoLocation">;
}
declare module "expo-location/build/ExpoLocation.web.js" {
  declare module.exports: $Exports<"expo-location/build/ExpoLocation.web">;
}
declare module "expo-location/build/Location.js" {
  declare module.exports: $Exports<"expo-location/build/Location">;
}
