// flow-typed signature: 77f5a86b7da3f379640c59c3847e8435
// flow-typed version: <<STUB>>/expo-document-picker_v^8.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-document-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "expo-document-picker" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "expo-document-picker/build/ExpoDocumentPicker" {
  declare module.exports: any;
}

declare module "expo-document-picker/build/ExpoDocumentPicker.web" {
  declare module.exports: any;
}

declare module "expo-document-picker/build" {
  declare module.exports: any;
}

declare module "expo-document-picker/build/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "expo-document-picker/build/ExpoDocumentPicker.js" {
  declare module.exports: $Exports<
    "expo-document-picker/build/ExpoDocumentPicker"
  >;
}
declare module "expo-document-picker/build/ExpoDocumentPicker.web.js" {
  declare module.exports: $Exports<
    "expo-document-picker/build/ExpoDocumentPicker.web"
  >;
}
declare module "expo-document-picker/build/index" {
  declare module.exports: $Exports<"expo-document-picker/build">;
}
declare module "expo-document-picker/build/index.js" {
  declare module.exports: $Exports<"expo-document-picker/build">;
}
declare module "expo-document-picker/build/types.js" {
  declare module.exports: $Exports<"expo-document-picker/build/types">;
}
