// flow-typed signature: a0469f06dff4dc51b86eaecc7a89c309
// flow-typed version: <<STUB>>/nodejs-mobile-react-native_v^0.4.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodejs-mobile-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodejs-mobile-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/builtin_modules/rn-bridge' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/constants' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/loader' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/binding' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/chained-batch' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/iterator' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/leveldown' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros/example/example' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/bin' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/build-test' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/optional' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/server' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/status' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/create-node-structure' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/module-postlink' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/patch-package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/builtin_modules/rn-bridge/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/builtin_modules/rn-bridge'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/builtin_modules/rn-bridge/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/builtin_modules/rn-bridge'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/constants.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/constants'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/loader.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/loader'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/binding.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/binding'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/chained-batch.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/chained-batch'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/iterator.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/iterator'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/leveldown.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/leveldown/leveldown'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros/example/example.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros/example/example'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/napi-macros'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/bin.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/bin'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/build-test.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/build-test'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/optional.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/node_modules/node-gyp-build/optional'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/server.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/server'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/status.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/out/nodejs-project/status'>;
}
declare module 'nodejs-mobile-react-native/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native'>;
}
declare module 'nodejs-mobile-react-native/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native'>;
}
declare module 'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main'>;
}
declare module 'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge'>;
}
declare module 'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge'>;
}
declare module 'nodejs-mobile-react-native/scripts/create-node-structure.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/create-node-structure'>;
}
declare module 'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override'>;
}
declare module 'nodejs-mobile-react-native/scripts/module-postlink.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/module-postlink'>;
}
declare module 'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload'>;
}
declare module 'nodejs-mobile-react-native/scripts/patch-package.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/patch-package'>;
}
