// flow-typed signature: 305f008641632516c1699794dea767f0
// flow-typed version: <<STUB>>/nodejs-mobile-react-native_v^0.3.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodejs-mobile-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodejs-mobile-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/builtin_modules/rn-bridge/index' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/constants' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/index' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/loader' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/chained-batch' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/iterator' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/leveldown' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/include_dirs' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/tools/1to2' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/server' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/status' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge/index' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/create-node-structure' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/module-postlink' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload' {
  declare module.exports: any;
}

declare module 'nodejs-mobile-react-native/scripts/patch-package' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/builtin_modules/rn-bridge/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/builtin_modules/rn-bridge/index'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/constants.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/constants'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/index'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/loader.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/loader'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/chained-batch.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/chained-batch'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/iterator.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/iterator'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/leveldown.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/leveldown'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/include_dirs.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/include_dirs'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/tools/1to2.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/node_modules/leveldown/node_modules/nan/tools/1to2'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/server.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/server'>;
}
declare module 'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/status.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/android/build/intermediates/library_assets/debug/packageDebugAssets/out/nodejs-project/status'>;
}
declare module 'nodejs-mobile-react-native/index' {
  declare module.exports: $Exports<'nodejs-mobile-react-native'>;
}
declare module 'nodejs-mobile-react-native/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native'>;
}
declare module 'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/install/resources/nodejs-assets/nodejs-project/sample-main'>;
}
declare module 'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge/index.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/install/resources/nodejs-modules/builtin_modules/rn-bridge/index'>;
}
declare module 'nodejs-mobile-react-native/scripts/create-node-structure.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/create-node-structure'>;
}
declare module 'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/ios-create-plists-and-dlopen-override'>;
}
declare module 'nodejs-mobile-react-native/scripts/module-postlink.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/module-postlink'>;
}
declare module 'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/override-dlopen-paths-preload'>;
}
declare module 'nodejs-mobile-react-native/scripts/patch-package.js' {
  declare module.exports: $Exports<'nodejs-mobile-react-native/scripts/patch-package'>;
}
