// flow-typed signature: 4028ddf0ab3ff5c13e44152df8a1db53
// flow-typed version: <<STUB>>/noderify_v^3.0.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noderify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'noderify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'noderify/bin' {
  declare module.exports: any;
}

declare module 'noderify/deterministic' {
  declare module.exports: any;
}

declare module 'noderify/inject' {
  declare module.exports: any;
}

declare module 'noderify/pack' {
  declare module.exports: any;
}

declare module 'noderify/test/fbb' {
  declare module.exports: any;
}

declare module 'noderify/test/missing' {
  declare module.exports: any;
}

declare module 'noderify/test/native' {
  declare module.exports: any;
}

declare module 'noderify/test/self-reference' {
  declare module.exports: any;
}

// Filename aliases
declare module 'noderify/bin.js' {
  declare module.exports: $Exports<'noderify/bin'>;
}
declare module 'noderify/deterministic.js' {
  declare module.exports: $Exports<'noderify/deterministic'>;
}
declare module 'noderify/index' {
  declare module.exports: $Exports<'noderify'>;
}
declare module 'noderify/index.js' {
  declare module.exports: $Exports<'noderify'>;
}
declare module 'noderify/inject.js' {
  declare module.exports: $Exports<'noderify/inject'>;
}
declare module 'noderify/pack.js' {
  declare module.exports: $Exports<'noderify/pack'>;
}
declare module 'noderify/test/fbb.js' {
  declare module.exports: $Exports<'noderify/test/fbb'>;
}
declare module 'noderify/test/missing.js' {
  declare module.exports: $Exports<'noderify/test/missing'>;
}
declare module 'noderify/test/native.js' {
  declare module.exports: $Exports<'noderify/test/native'>;
}
declare module 'noderify/test/self-reference.js' {
  declare module.exports: $Exports<'noderify/test/self-reference'>;
}
