// flow-typed signature: 9069a37df2b8d85d42e0cae3b9fc67d5
// flow-typed version: <<STUB>>/react-navigation-tabs_v0.1.0-alpha.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-tabs/dist/index' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/utils/createTabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/utils/withDimensions' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/TabBarBottom' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/TabBarIcon' {
  declare module.exports: any;
}

declare module 'react-navigation-tabs/dist/views/TabBarTop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-tabs/dist/index.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/index'>;
}
declare module 'react-navigation-tabs/dist/navigators/createBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createMaterialBottomTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/navigators/createMaterialTopTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/utils/createTabNavigator.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/utils/createTabNavigator'>;
}
declare module 'react-navigation-tabs/dist/utils/withDimensions.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/utils/withDimensions'>;
}
declare module 'react-navigation-tabs/dist/views/TabBarBottom.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/TabBarBottom'>;
}
declare module 'react-navigation-tabs/dist/views/TabBarIcon.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/TabBarIcon'>;
}
declare module 'react-navigation-tabs/dist/views/TabBarTop.js' {
  declare module.exports: $Exports<'react-navigation-tabs/dist/views/TabBarTop'>;
}
