// flow-typed signature: 9d1d66da60c2c7b3af321833f72c521a
// flow-typed version: <<STUB>>/react-native-indicators_v^0.17.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-indicators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-indicators" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-indicators/src/components/ball-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/ball-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/bar-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/bar-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/dot-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/dot-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/material-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/material-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/pacman-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/pacman-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/pulse-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/pulse-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/skype-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/skype-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/ui-activity-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/ui-activity-indicator/styles" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/wave-indicator" {
  declare module.exports: any;
}

declare module "react-native-indicators/src/components/wave-indicator/styles" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-indicators/index" {
  declare module.exports: $Exports<"react-native-indicators">;
}
declare module "react-native-indicators/index.js" {
  declare module.exports: $Exports<"react-native-indicators">;
}
declare module "react-native-indicators/src/components/ball-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ball-indicator"
  >;
}
declare module "react-native-indicators/src/components/ball-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ball-indicator"
  >;
}
declare module "react-native-indicators/src/components/ball-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ball-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/bar-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/bar-indicator"
  >;
}
declare module "react-native-indicators/src/components/bar-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/bar-indicator"
  >;
}
declare module "react-native-indicators/src/components/bar-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/bar-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/dot-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/dot-indicator"
  >;
}
declare module "react-native-indicators/src/components/dot-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/dot-indicator"
  >;
}
declare module "react-native-indicators/src/components/dot-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/dot-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/indicator"
  >;
}
declare module "react-native-indicators/src/components/indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/indicator"
  >;
}
declare module "react-native-indicators/src/components/material-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/material-indicator"
  >;
}
declare module "react-native-indicators/src/components/material-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/material-indicator"
  >;
}
declare module "react-native-indicators/src/components/material-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/material-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/pacman-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pacman-indicator"
  >;
}
declare module "react-native-indicators/src/components/pacman-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pacman-indicator"
  >;
}
declare module "react-native-indicators/src/components/pacman-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pacman-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/pulse-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pulse-indicator"
  >;
}
declare module "react-native-indicators/src/components/pulse-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pulse-indicator"
  >;
}
declare module "react-native-indicators/src/components/pulse-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/pulse-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/skype-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/skype-indicator"
  >;
}
declare module "react-native-indicators/src/components/skype-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/skype-indicator"
  >;
}
declare module "react-native-indicators/src/components/skype-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/skype-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/ui-activity-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ui-activity-indicator"
  >;
}
declare module "react-native-indicators/src/components/ui-activity-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ui-activity-indicator"
  >;
}
declare module "react-native-indicators/src/components/ui-activity-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/ui-activity-indicator/styles"
  >;
}
declare module "react-native-indicators/src/components/wave-indicator/index" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/wave-indicator"
  >;
}
declare module "react-native-indicators/src/components/wave-indicator/index.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/wave-indicator"
  >;
}
declare module "react-native-indicators/src/components/wave-indicator/styles.js" {
  declare module.exports: $Exports<
    "react-native-indicators/src/components/wave-indicator/styles"
  >;
}
