// flow-typed signature: 73048ee9560a2c9fec3d8bfc7b44131c
// flow-typed version: <<STUB>>/react-native-linear-gradient_v^2.5.4/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-linear-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-linear-gradient/common' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.android' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-linear-gradient/common.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/common'>;
}
declare module 'react-native-linear-gradient/index.android.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.android'>;
}
declare module 'react-native-linear-gradient/index.ios.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.ios'>;
}
declare module 'react-native-linear-gradient/index' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
declare module 'react-native-linear-gradient/index.js' {
  declare module.exports: $Exports<'react-native-linear-gradient'>;
}
declare module 'react-native-linear-gradient/index.windows.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.windows'>;
}
