// flow-typed signature: 5f3cec37d036a7ab39dc56b31b3cee1c
// flow-typed version: <<STUB>>/react-native-tab-view_v^2.6.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tab-view/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/memoize' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/Pager' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/SceneMap' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/SceneView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/TabBarIndicator' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/TabBarItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/TabView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/memoize' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/Pager' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/SceneMap' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/SceneView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/TabBarIndicator' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/TabBarItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/TabView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/lib/module/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tab-view/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs'>;
}
declare module 'react-native-tab-view/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs'>;
}
declare module 'react-native-tab-view/lib/commonjs/memoize.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/memoize'>;
}
declare module 'react-native-tab-view/lib/commonjs/Pager.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/Pager'>;
}
declare module 'react-native-tab-view/lib/commonjs/SceneMap.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/SceneMap'>;
}
declare module 'react-native-tab-view/lib/commonjs/SceneView.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/SceneView'>;
}
declare module 'react-native-tab-view/lib/commonjs/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/TabBar'>;
}
declare module 'react-native-tab-view/lib/commonjs/TabBarIndicator.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/TabBarIndicator'>;
}
declare module 'react-native-tab-view/lib/commonjs/TabBarItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/TabBarItem'>;
}
declare module 'react-native-tab-view/lib/commonjs/TabView.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/TabView'>;
}
declare module 'react-native-tab-view/lib/commonjs/TouchableItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/TouchableItem'>;
}
declare module 'react-native-tab-view/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/commonjs/types'>;
}
declare module 'react-native-tab-view/lib/module/index' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module'>;
}
declare module 'react-native-tab-view/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module'>;
}
declare module 'react-native-tab-view/lib/module/memoize.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/memoize'>;
}
declare module 'react-native-tab-view/lib/module/Pager.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/Pager'>;
}
declare module 'react-native-tab-view/lib/module/SceneMap.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/SceneMap'>;
}
declare module 'react-native-tab-view/lib/module/SceneView.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/SceneView'>;
}
declare module 'react-native-tab-view/lib/module/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/TabBar'>;
}
declare module 'react-native-tab-view/lib/module/TabBarIndicator.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/TabBarIndicator'>;
}
declare module 'react-native-tab-view/lib/module/TabBarItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/TabBarItem'>;
}
declare module 'react-native-tab-view/lib/module/TabView.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/TabView'>;
}
declare module 'react-native-tab-view/lib/module/TouchableItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/TouchableItem'>;
}
declare module 'react-native-tab-view/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-tab-view/lib/module/types'>;
}
