// flow-typed signature: 82e20bee7ad391b2b492ed63f2c92c83
// flow-typed version: <<STUB>>/react-native-node_v^3.3.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-node/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-node/bin.js' {
  declare module.exports: $Exports<'react-native-node/bin'>;
}
declare module 'react-native-node/index' {
  declare module.exports: $Exports<'react-native-node'>;
}
declare module 'react-native-node/index.js' {
  declare module.exports: $Exports<'react-native-node'>;
}
