// flow-typed signature: 06b6cda4585ec15f27bac9bcf43528e6
// flow-typed version: <<STUB>>/react-native-keep-awake_v^4.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keep-awake'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-keep-awake" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "react-native-keep-awake/index" {
  declare module.exports: $Exports<"react-native-keep-awake">;
}
declare module "react-native-keep-awake/index.js" {
  declare module.exports: $Exports<"react-native-keep-awake">;
}
