// flow-typed signature: cffe39cc86d6aa3103b1d482f2b1bfa7
// flow-typed version: <<STUB>>/react-native-hooks_v^0.9.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-hooks" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-hooks/lib/useAccessibilityInfo" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useAppState" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useBackHandler" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useCameraRoll" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useClipboard" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useDeviceOrientation" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useDimensions" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useInteractionManager" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useKeyboard" {
  declare module.exports: any;
}

declare module "react-native-hooks/lib/useLayout" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-hooks/index" {
  declare module.exports: $Exports<"react-native-hooks">;
}
declare module "react-native-hooks/index.js" {
  declare module.exports: $Exports<"react-native-hooks">;
}
declare module "react-native-hooks/lib/useAccessibilityInfo.js" {
  declare module.exports: $Exports<
    "react-native-hooks/lib/useAccessibilityInfo"
  >;
}
declare module "react-native-hooks/lib/useAppState.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useAppState">;
}
declare module "react-native-hooks/lib/useBackHandler.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useBackHandler">;
}
declare module "react-native-hooks/lib/useCameraRoll.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useCameraRoll">;
}
declare module "react-native-hooks/lib/useClipboard.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useClipboard">;
}
declare module "react-native-hooks/lib/useDeviceOrientation.js" {
  declare module.exports: $Exports<
    "react-native-hooks/lib/useDeviceOrientation"
  >;
}
declare module "react-native-hooks/lib/useDimensions.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useDimensions">;
}
declare module "react-native-hooks/lib/useInteractionManager.js" {
  declare module.exports: $Exports<
    "react-native-hooks/lib/useInteractionManager"
  >;
}
declare module "react-native-hooks/lib/useKeyboard.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useKeyboard">;
}
declare module "react-native-hooks/lib/useLayout.js" {
  declare module.exports: $Exports<"react-native-hooks/lib/useLayout">;
}
