// flow-typed signature: dfd4c08ea9426e464f4b3c2b0f9cf562
// flow-typed version: <<STUB>>/react-native-splash-screen_v^3.2.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-splash-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-splash-screen" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "react-native-splash-screen/index" {
  declare module.exports: $Exports<"react-native-splash-screen">;
}
declare module "react-native-splash-screen/index.js" {
  declare module.exports: $Exports<"react-native-splash-screen">;
}
