// flow-typed signature: b0d5c65c1d87a86c5ca54fbbceef8df1
// flow-typed version: <<STUB>>/react-native-image-resizer_v1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-resizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-resizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-image-resizer/index.android' {
  declare module.exports: any;
}

declare module 'react-native-image-resizer/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-image-resizer/index.android.js' {
  declare module.exports: $Exports<'react-native-image-resizer/index.android'>;
}
declare module 'react-native-image-resizer/index.ios.js' {
  declare module.exports: $Exports<'react-native-image-resizer/index.ios'>;
}
