// flow-typed signature: ed26dd956ae2b792f69f582196fae0c9
// flow-typed version: <<STUB>>/react-native-android-open-settings_v^1.3.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-android-open-settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-android-open-settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-android-open-settings/index' {
  declare module.exports: $Exports<'react-native-android-open-settings'>;
}
declare module 'react-native-android-open-settings/index.js' {
  declare module.exports: $Exports<'react-native-android-open-settings'>;
}
