// flow-typed signature: 7f207179117efdfa83a5e943e0bc8c86
// flow-typed version: <<STUB>>/react-native-remote-svg_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-remote-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-remote-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-remote-svg/SvgImage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-remote-svg/index' {
  declare module.exports: $Exports<'react-native-remote-svg'>;
}
declare module 'react-native-remote-svg/index.js' {
  declare module.exports: $Exports<'react-native-remote-svg'>;
}
declare module 'react-native-remote-svg/SvgImage.js' {
  declare module.exports: $Exports<'react-native-remote-svg/SvgImage'>;
}
