// flow-typed signature: 350ef3ab5bb1a6730e152ea0c761505d
// flow-typed version: <<STUB>>/react-native-scale-bar_v^1.0.6/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-scale-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-scale-bar" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-scale-bar/src/constants" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/HorizontalLine" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/ScaleBarModel" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/ScaleBarModel.test" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/ScaleBarView" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/ScaleText" {
  declare module.exports: any;
}

declare module "react-native-scale-bar/src/VerticalLine" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-scale-bar/index" {
  declare module.exports: $Exports<"react-native-scale-bar">;
}
declare module "react-native-scale-bar/index.js" {
  declare module.exports: $Exports<"react-native-scale-bar">;
}
declare module "react-native-scale-bar/src/constants.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/constants">;
}
declare module "react-native-scale-bar/src/HorizontalLine.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/HorizontalLine">;
}
declare module "react-native-scale-bar/src/ScaleBarModel.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/ScaleBarModel">;
}
declare module "react-native-scale-bar/src/ScaleBarModel.test.js" {
  declare module.exports: $Exports<
    "react-native-scale-bar/src/ScaleBarModel.test"
  >;
}
declare module "react-native-scale-bar/src/ScaleBarView.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/ScaleBarView">;
}
declare module "react-native-scale-bar/src/ScaleText.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/ScaleText">;
}
declare module "react-native-scale-bar/src/VerticalLine.js" {
  declare module.exports: $Exports<"react-native-scale-bar/src/VerticalLine">;
}
