// flow-typed signature: 32e61b54dab745d2888180bc5cd916db
// flow-typed version: <<STUB>>/react-native-share_v^3.1.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-share'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-share" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-share/changelog" {
  declare module.exports: any;
}

declare module "react-native-share/components/Button" {
  declare module.exports: any;
}

declare module "react-native-share/components/Overlay" {
  declare module.exports: any;
}

declare module "react-native-share/components/Sheet" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-share/changelog.js" {
  declare module.exports: $Exports<"react-native-share/changelog">;
}
declare module "react-native-share/components/Button.js" {
  declare module.exports: $Exports<"react-native-share/components/Button">;
}
declare module "react-native-share/components/Overlay.js" {
  declare module.exports: $Exports<"react-native-share/components/Overlay">;
}
declare module "react-native-share/components/Sheet.js" {
  declare module.exports: $Exports<"react-native-share/components/Sheet">;
}
declare module "react-native-share/index" {
  declare module.exports: $Exports<"react-native-share">;
}
declare module "react-native-share/index.js" {
  declare module.exports: $Exports<"react-native-share">;
}
