// flow-typed signature: 513ed5afbf7ef30fedf6ca8cee7dee0a
// flow-typed version: <<STUB>>/react-native-xml2js_v^1.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-xml2js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-xml2js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-xml2js/lib/bom' {
  declare module.exports: any;
}

declare module 'react-native-xml2js/lib/builder' {
  declare module.exports: any;
}

declare module 'react-native-xml2js/lib/defaults' {
  declare module.exports: any;
}

declare module 'react-native-xml2js/lib/parser' {
  declare module.exports: any;
}

declare module 'react-native-xml2js/lib/processors' {
  declare module.exports: any;
}

declare module 'react-native-xml2js/lib/xml2js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-xml2js/lib/bom.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/bom'>;
}
declare module 'react-native-xml2js/lib/builder.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/builder'>;
}
declare module 'react-native-xml2js/lib/defaults.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/defaults'>;
}
declare module 'react-native-xml2js/lib/parser.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/parser'>;
}
declare module 'react-native-xml2js/lib/processors.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/processors'>;
}
declare module 'react-native-xml2js/lib/xml2js.js' {
  declare module.exports: $Exports<'react-native-xml2js/lib/xml2js'>;
}
