// flow-typed signature: dcf6f2b7295c754891ee34d3b5ca9340
// flow-typed version: <<STUB>>/react-native-build-config_v^0.3.2/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-build-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-build-config" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-native-build-config/lib" {
  declare module.exports: any;
}

declare module "react-native-build-config/react-native.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-native-build-config/lib/index" {
  declare module.exports: $Exports<"react-native-build-config/lib">;
}
declare module "react-native-build-config/lib/index.js" {
  declare module.exports: $Exports<"react-native-build-config/lib">;
}
declare module "react-native-build-config/react-native.config.js" {
  declare module.exports: $Exports<
    "react-native-build-config/react-native.config"
  >;
}
