// flow-typed signature: ee4c47e5bcba7c52ca5a1968b2733c42
// flow-typed version: <<STUB>>/react-navigation-stack_v^2.3.11/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-stack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-navigation-stack" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-navigation-stack/lib/commonjs" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/navigators/createStackNavigator" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/types" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/utils/useTheme" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/utils/validateDeprecatedConfig" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/utils/validateDeprecatedOptions" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/CardStyleInterpolators" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/HeaderStyleInterpolators" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionPresets" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionSpecs" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/types" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/CardAnimationContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/conditional" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/debounce" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/GestureHandlerRefContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/getDistanceForDirection" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/getInvertedMultiplier" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/HeaderHeightContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/memoize" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/useCardAnimation" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/useGestureHandlerRef" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/utils/useHeaderHeight" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/BorderlessButton" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/Header" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackButton" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackground" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderContainer" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderSegment" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderTitle" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/KeyboardManager" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/MaskedView" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/MaskedView.native" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/SafeAreaProviderCompat" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/Card" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardContainer" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardStack" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/StackView" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/vendor/views/TouchableItem" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/commonjs/views/StackView" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/navigators/createStackNavigator" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/types" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/utils/useTheme" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/utils/validateDeprecatedConfig" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/utils/validateDeprecatedOptions" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/CardStyleInterpolators" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/HeaderStyleInterpolators" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionPresets" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionSpecs" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/types" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/CardAnimationContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/conditional" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/debounce" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/GestureHandlerRefContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/getDistanceForDirection" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/getInvertedMultiplier" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/HeaderHeightContext" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/memoize" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/useCardAnimation" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/useGestureHandlerRef" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/utils/useHeaderHeight" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/BorderlessButton" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/Header" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackButton" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackground" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderContainer" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderSegment" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderTitle" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/KeyboardManager" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/MaskedView" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/MaskedView.native" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/SafeAreaProviderCompat" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Stack/Card" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Stack/CardContainer" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Stack/CardStack" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/Stack/StackView" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/vendor/views/TouchableItem" {
  declare module.exports: any;
}

declare module "react-navigation-stack/lib/module/views/StackView" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-navigation-stack/lib/commonjs/index" {
  declare module.exports: $Exports<"react-navigation-stack/lib/commonjs">;
}
declare module "react-navigation-stack/lib/commonjs/index.js" {
  declare module.exports: $Exports<"react-navigation-stack/lib/commonjs">;
}
declare module "react-navigation-stack/lib/commonjs/navigators/createStackNavigator.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/navigators/createStackNavigator"
  >;
}
declare module "react-navigation-stack/lib/commonjs/types.js" {
  declare module.exports: $Exports<"react-navigation-stack/lib/commonjs/types">;
}
declare module "react-navigation-stack/lib/commonjs/utils/useTheme.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/utils/useTheme"
  >;
}
declare module "react-navigation-stack/lib/commonjs/utils/validateDeprecatedConfig.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/utils/validateDeprecatedConfig"
  >;
}
declare module "react-navigation-stack/lib/commonjs/utils/validateDeprecatedOptions.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/utils/validateDeprecatedOptions"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/index" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/index.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/CardStyleInterpolators.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/CardStyleInterpolators"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/HeaderStyleInterpolators.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/HeaderStyleInterpolators"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionPresets.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionPresets"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionSpecs.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/TransitionConfigs/TransitionSpecs"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/types.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/types"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/CardAnimationContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/CardAnimationContext"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/conditional.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/conditional"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/debounce.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/debounce"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/GestureHandlerRefContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/GestureHandlerRefContext"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/getDistanceForDirection.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/getDistanceForDirection"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/getInvertedMultiplier.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/getInvertedMultiplier"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/HeaderHeightContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/HeaderHeightContext"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/memoize.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/memoize"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/useCardAnimation.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/useCardAnimation"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/useGestureHandlerRef.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/useGestureHandlerRef"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/utils/useHeaderHeight.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/utils/useHeaderHeight"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/BorderlessButton.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/BorderlessButton"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/Header.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/Header"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackButton.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackButton"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackground.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderBackground"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderContainer.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderContainer"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderSegment.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderSegment"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderTitle.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Header/HeaderTitle"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/KeyboardManager.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/KeyboardManager"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/MaskedView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/MaskedView"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/MaskedView.native.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/MaskedView.native"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/SafeAreaProviderCompat.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/SafeAreaProviderCompat"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/Card.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Stack/Card"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardContainer.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardContainer"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardStack.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Stack/CardStack"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/Stack/StackView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/Stack/StackView"
  >;
}
declare module "react-navigation-stack/lib/commonjs/vendor/views/TouchableItem.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/vendor/views/TouchableItem"
  >;
}
declare module "react-navigation-stack/lib/commonjs/views/StackView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/commonjs/views/StackView"
  >;
}
declare module "react-navigation-stack/lib/module/index" {
  declare module.exports: $Exports<"react-navigation-stack/lib/module">;
}
declare module "react-navigation-stack/lib/module/index.js" {
  declare module.exports: $Exports<"react-navigation-stack/lib/module">;
}
declare module "react-navigation-stack/lib/module/navigators/createStackNavigator.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/navigators/createStackNavigator"
  >;
}
declare module "react-navigation-stack/lib/module/types.js" {
  declare module.exports: $Exports<"react-navigation-stack/lib/module/types">;
}
declare module "react-navigation-stack/lib/module/utils/useTheme.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/utils/useTheme"
  >;
}
declare module "react-navigation-stack/lib/module/utils/validateDeprecatedConfig.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/utils/validateDeprecatedConfig"
  >;
}
declare module "react-navigation-stack/lib/module/utils/validateDeprecatedOptions.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/utils/validateDeprecatedOptions"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/index" {
  declare module.exports: $Exports<"react-navigation-stack/lib/module/vendor">;
}
declare module "react-navigation-stack/lib/module/vendor/index.js" {
  declare module.exports: $Exports<"react-navigation-stack/lib/module/vendor">;
}
declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/CardStyleInterpolators.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/TransitionConfigs/CardStyleInterpolators"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/HeaderStyleInterpolators.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/TransitionConfigs/HeaderStyleInterpolators"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionPresets.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionPresets"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionSpecs.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/TransitionConfigs/TransitionSpecs"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/types.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/types"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/CardAnimationContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/CardAnimationContext"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/conditional.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/conditional"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/debounce.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/debounce"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/GestureHandlerRefContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/GestureHandlerRefContext"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/getDistanceForDirection.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/getDistanceForDirection"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/getInvertedMultiplier.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/getInvertedMultiplier"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/HeaderHeightContext.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/HeaderHeightContext"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/memoize.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/memoize"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/useCardAnimation.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/useCardAnimation"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/useGestureHandlerRef.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/useGestureHandlerRef"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/utils/useHeaderHeight.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/utils/useHeaderHeight"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/BorderlessButton.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/BorderlessButton"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/Header.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/Header"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackButton.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackButton"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackground.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/HeaderBackground"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderContainer.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/HeaderContainer"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderSegment.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/HeaderSegment"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Header/HeaderTitle.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Header/HeaderTitle"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/KeyboardManager.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/KeyboardManager"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/MaskedView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/MaskedView"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/MaskedView.native.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/MaskedView.native"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/SafeAreaProviderCompat.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/SafeAreaProviderCompat"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Stack/Card.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Stack/Card"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Stack/CardContainer.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Stack/CardContainer"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Stack/CardStack.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Stack/CardStack"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/Stack/StackView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/Stack/StackView"
  >;
}
declare module "react-navigation-stack/lib/module/vendor/views/TouchableItem.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/vendor/views/TouchableItem"
  >;
}
declare module "react-navigation-stack/lib/module/views/StackView.js" {
  declare module.exports: $Exports<
    "react-navigation-stack/lib/module/views/StackView"
  >;
}
