// flow-typed signature: b25b299c68574da96675fbf90396f62d
// flow-typed version: <<STUB>>/react-native-v8_v0.61.5-patch.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-v8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-native-v8" {
  declare module.exports: any;
}
