// flow-typed signature: d49b6088b22138a8ecb3fe535524024e
// flow-typed version: <<STUB>>/react-navigation-hooks_v^1.0.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation-hooks/dist/Hooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation-hooks/dist/Hooks.js' {
  declare module.exports: $Exports<'react-navigation-hooks/dist/Hooks'>;
}
