// flow-typed signature: 1102e94da271b5feb062bb693187e04f
// flow-typed version: <<STUB>>/react-native-tab-view_v^2.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tab-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tab-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tab-view/src/index' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/Pager' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/SceneMap' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/SceneView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabBarIndicator' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabBarItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TabView' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-native-tab-view/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tab-view/src/index.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/index'>;
}
declare module 'react-native-tab-view/src/Pager.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/Pager'>;
}
declare module 'react-native-tab-view/src/SceneMap.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/SceneMap'>;
}
declare module 'react-native-tab-view/src/SceneView.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/SceneView'>;
}
declare module 'react-native-tab-view/src/TabBar.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabBar'>;
}
declare module 'react-native-tab-view/src/TabBarIndicator.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabBarIndicator'>;
}
declare module 'react-native-tab-view/src/TabBarItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabBarItem'>;
}
declare module 'react-native-tab-view/src/TabView.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TabView'>;
}
declare module 'react-native-tab-view/src/TouchableItem.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/TouchableItem'>;
}
declare module 'react-native-tab-view/src/types.js' {
  declare module.exports: $Exports<'react-native-tab-view/src/types'>;
}
