// flow-typed signature: ca9d51f3355918963a3ca9639417343f
// flow-typed version: <<STUB>>/react-native-network-info_v^5/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-network-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-network-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-network-info/NetworkInfo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-network-info/NetworkInfo.js' {
  declare module.exports: $Exports<'react-native-network-info/NetworkInfo'>;
}
