// flow-typed signature: c91996037d14f1ce6b8eace64d1fd50b
// flow-typed version: <<STUB>>/stacktrace-parser_v^0.1.4/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stacktrace-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stacktrace-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stacktrace-parser/dist/stack-trace-parser.cjs' {
  declare module.exports: any;
}

declare module 'stacktrace-parser/dist/stack-trace-parser.esm' {
  declare module.exports: any;
}

declare module 'stacktrace-parser/dist/stack-trace-parser.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stacktrace-parser/dist/stack-trace-parser.cjs.js' {
  declare module.exports: $Exports<'stacktrace-parser/dist/stack-trace-parser.cjs'>;
}
declare module 'stacktrace-parser/dist/stack-trace-parser.esm.js' {
  declare module.exports: $Exports<'stacktrace-parser/dist/stack-trace-parser.esm'>;
}
declare module 'stacktrace-parser/dist/stack-trace-parser.umd.js' {
  declare module.exports: $Exports<'stacktrace-parser/dist/stack-trace-parser.umd'>;
}
