// flow-typed signature: e0a8b6bdb4f3a8af4428f3d48450d1c7
// flow-typed version: <<STUB>>/wd_v^1.4.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wd/browser-scripts/safe-execute-async' {
  declare module.exports: any;
}

declare module 'wd/browser-scripts/safe-execute' {
  declare module.exports: any;
}

declare module 'wd/browser-scripts/wait-for-cond-in-browser' {
  declare module.exports: any;
}

declare module 'wd/build/safe-execute-async' {
  declare module.exports: any;
}

declare module 'wd/build/safe-execute' {
  declare module.exports: any;
}

declare module 'wd/build/wait-for-cond-in-browser' {
  declare module.exports: any;
}

declare module 'wd/doc/mapping-builder' {
  declare module.exports: any;
}

declare module 'wd/examples/async/add-method' {
  declare module.exports: any;
}

declare module 'wd/examples/async/browserstack.ie' {
  declare module.exports: any;
}

declare module 'wd/examples/async/browserstack' {
  declare module.exports: any;
}

declare module 'wd/examples/async/chrome' {
  declare module.exports: any;
}

declare module 'wd/examples/async/firefox' {
  declare module.exports: any;
}

declare module 'wd/examples/async/kobiton' {
  declare module.exports: any;
}

declare module 'wd/examples/async/sauce.ie' {
  declare module.exports: any;
}

declare module 'wd/examples/async/sauce' {
  declare module.exports: any;
}

declare module 'wd/examples/deprecated/deprecated.chain' {
  declare module.exports: any;
}

declare module 'wd/examples/deprecated/wait-for-simple' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/add-method-async' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/add-method-no-chain' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/add-method' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/browserstack.ie' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/browserstack' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/chained-el-func-call' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/chrome' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/chromedriver' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/complex' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/drag-n-drop' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/external-promise' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/firefox' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/harmony' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/helper' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/kobiton' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/mocha-harmony' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/mocha-specs' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/no-chain' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/sauce-connect' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/sauce.ie' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/sauce' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/wait-for-custom' {
  declare module.exports: any;
}

declare module 'wd/examples/promise/wait-for-simple' {
  declare module.exports: any;
}

declare module 'wd/gulpfile' {
  declare module.exports: any;
}

declare module 'wd/lib/actions' {
  declare module.exports: any;
}

declare module 'wd/lib/asserters' {
  declare module.exports: any;
}

declare module 'wd/lib/bin' {
  declare module.exports: any;
}

declare module 'wd/lib/callbacks' {
  declare module.exports: any;
}

declare module 'wd/lib/commands' {
  declare module.exports: any;
}

declare module 'wd/lib/config' {
  declare module.exports: any;
}

declare module 'wd/lib/deprecated-chain' {
  declare module.exports: any;
}

declare module 'wd/lib/element-commands' {
  declare module.exports: any;
}

declare module 'wd/lib/element' {
  declare module.exports: any;
}

declare module 'wd/lib/http-utils' {
  declare module.exports: any;
}

declare module 'wd/lib/jsonwire-errors' {
  declare module.exports: any;
}

declare module 'wd/lib/lodash' {
  declare module.exports: any;
}

declare module 'wd/lib/main' {
  declare module.exports: any;
}

declare module 'wd/lib/promise-webdriver' {
  declare module.exports: any;
}

declare module 'wd/lib/special-keys' {
  declare module.exports: any;
}

declare module 'wd/lib/tmp' {
  declare module.exports: any;
}

declare module 'wd/lib/utils' {
  declare module.exports: any;
}

declare module 'wd/lib/webdriver' {
  declare module.exports: any;
}

declare module 'wd/scripts/build-browser-scripts' {
  declare module.exports: any;
}

declare module 'wd/test/coverage/run_tests' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/async' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/basic-specs' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/deprecated-chain-specs' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/promise-chain-specs' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/promise-no-chain-specs' {
  declare module.exports: any;
}

declare module 'wd/test/e2e/sauce-helpers-specs' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/env' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/express-helper' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/make-tool' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/mobile_env' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/quit-gracefully' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/setup' {
  declare module.exports: any;
}

declare module 'wd/test/helpers/skip' {
  declare module.exports: any;
}

declare module 'wd/test/midway/add-methods-async-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/add-methods-pc-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/add-methods-pnc-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/api-el-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/api-el-suffix-base' {
  declare module.exports: any;
}

declare module 'wd/test/midway/api-exec-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/api-nav-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/api-various-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/asserters-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/attach-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/chaining-scope-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/chaining-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/element-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/external-promises-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/frame-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/keying-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/midway-base' {
  declare module.exports: any;
}

declare module 'wd/test/midway/mobile-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/multi/config-http-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/multi/init-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/multi/status-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-class-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-css-sel-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-css-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-id-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-link-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-name-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-partial-link-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-tag-name-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/suffixes/api-el-by-xpath-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/typing-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/wait-for-1-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/wait-for-2-specs' {
  declare module.exports: any;
}

declare module 'wd/test/midway/window-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/callback-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/http-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/init-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/mjson-actions-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/mjson-specs' {
  declare module.exports: any;
}

declare module 'wd/test/specs/remote-specs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wd/browser-scripts/safe-execute-async.js' {
  declare module.exports: $Exports<'wd/browser-scripts/safe-execute-async'>;
}
declare module 'wd/browser-scripts/safe-execute.js' {
  declare module.exports: $Exports<'wd/browser-scripts/safe-execute'>;
}
declare module 'wd/browser-scripts/wait-for-cond-in-browser.js' {
  declare module.exports: $Exports<'wd/browser-scripts/wait-for-cond-in-browser'>;
}
declare module 'wd/build/safe-execute-async.js' {
  declare module.exports: $Exports<'wd/build/safe-execute-async'>;
}
declare module 'wd/build/safe-execute.js' {
  declare module.exports: $Exports<'wd/build/safe-execute'>;
}
declare module 'wd/build/wait-for-cond-in-browser.js' {
  declare module.exports: $Exports<'wd/build/wait-for-cond-in-browser'>;
}
declare module 'wd/doc/mapping-builder.js' {
  declare module.exports: $Exports<'wd/doc/mapping-builder'>;
}
declare module 'wd/examples/async/add-method.js' {
  declare module.exports: $Exports<'wd/examples/async/add-method'>;
}
declare module 'wd/examples/async/browserstack.ie.js' {
  declare module.exports: $Exports<'wd/examples/async/browserstack.ie'>;
}
declare module 'wd/examples/async/browserstack.js' {
  declare module.exports: $Exports<'wd/examples/async/browserstack'>;
}
declare module 'wd/examples/async/chrome.js' {
  declare module.exports: $Exports<'wd/examples/async/chrome'>;
}
declare module 'wd/examples/async/firefox.js' {
  declare module.exports: $Exports<'wd/examples/async/firefox'>;
}
declare module 'wd/examples/async/kobiton.js' {
  declare module.exports: $Exports<'wd/examples/async/kobiton'>;
}
declare module 'wd/examples/async/sauce.ie.js' {
  declare module.exports: $Exports<'wd/examples/async/sauce.ie'>;
}
declare module 'wd/examples/async/sauce.js' {
  declare module.exports: $Exports<'wd/examples/async/sauce'>;
}
declare module 'wd/examples/deprecated/deprecated.chain.js' {
  declare module.exports: $Exports<'wd/examples/deprecated/deprecated.chain'>;
}
declare module 'wd/examples/deprecated/wait-for-simple.js' {
  declare module.exports: $Exports<'wd/examples/deprecated/wait-for-simple'>;
}
declare module 'wd/examples/promise/add-method-async.js' {
  declare module.exports: $Exports<'wd/examples/promise/add-method-async'>;
}
declare module 'wd/examples/promise/add-method-no-chain.js' {
  declare module.exports: $Exports<'wd/examples/promise/add-method-no-chain'>;
}
declare module 'wd/examples/promise/add-method.js' {
  declare module.exports: $Exports<'wd/examples/promise/add-method'>;
}
declare module 'wd/examples/promise/browserstack.ie.js' {
  declare module.exports: $Exports<'wd/examples/promise/browserstack.ie'>;
}
declare module 'wd/examples/promise/browserstack.js' {
  declare module.exports: $Exports<'wd/examples/promise/browserstack'>;
}
declare module 'wd/examples/promise/chained-el-func-call.js' {
  declare module.exports: $Exports<'wd/examples/promise/chained-el-func-call'>;
}
declare module 'wd/examples/promise/chrome.js' {
  declare module.exports: $Exports<'wd/examples/promise/chrome'>;
}
declare module 'wd/examples/promise/chromedriver.js' {
  declare module.exports: $Exports<'wd/examples/promise/chromedriver'>;
}
declare module 'wd/examples/promise/complex.js' {
  declare module.exports: $Exports<'wd/examples/promise/complex'>;
}
declare module 'wd/examples/promise/drag-n-drop.js' {
  declare module.exports: $Exports<'wd/examples/promise/drag-n-drop'>;
}
declare module 'wd/examples/promise/external-promise.js' {
  declare module.exports: $Exports<'wd/examples/promise/external-promise'>;
}
declare module 'wd/examples/promise/firefox.js' {
  declare module.exports: $Exports<'wd/examples/promise/firefox'>;
}
declare module 'wd/examples/promise/harmony.js' {
  declare module.exports: $Exports<'wd/examples/promise/harmony'>;
}
declare module 'wd/examples/promise/helper.js' {
  declare module.exports: $Exports<'wd/examples/promise/helper'>;
}
declare module 'wd/examples/promise/kobiton.js' {
  declare module.exports: $Exports<'wd/examples/promise/kobiton'>;
}
declare module 'wd/examples/promise/mocha-harmony.js' {
  declare module.exports: $Exports<'wd/examples/promise/mocha-harmony'>;
}
declare module 'wd/examples/promise/mocha-specs.js' {
  declare module.exports: $Exports<'wd/examples/promise/mocha-specs'>;
}
declare module 'wd/examples/promise/no-chain.js' {
  declare module.exports: $Exports<'wd/examples/promise/no-chain'>;
}
declare module 'wd/examples/promise/sauce-connect.js' {
  declare module.exports: $Exports<'wd/examples/promise/sauce-connect'>;
}
declare module 'wd/examples/promise/sauce.ie.js' {
  declare module.exports: $Exports<'wd/examples/promise/sauce.ie'>;
}
declare module 'wd/examples/promise/sauce.js' {
  declare module.exports: $Exports<'wd/examples/promise/sauce'>;
}
declare module 'wd/examples/promise/wait-for-custom.js' {
  declare module.exports: $Exports<'wd/examples/promise/wait-for-custom'>;
}
declare module 'wd/examples/promise/wait-for-simple.js' {
  declare module.exports: $Exports<'wd/examples/promise/wait-for-simple'>;
}
declare module 'wd/gulpfile.js' {
  declare module.exports: $Exports<'wd/gulpfile'>;
}
declare module 'wd/lib/actions.js' {
  declare module.exports: $Exports<'wd/lib/actions'>;
}
declare module 'wd/lib/asserters.js' {
  declare module.exports: $Exports<'wd/lib/asserters'>;
}
declare module 'wd/lib/bin.js' {
  declare module.exports: $Exports<'wd/lib/bin'>;
}
declare module 'wd/lib/callbacks.js' {
  declare module.exports: $Exports<'wd/lib/callbacks'>;
}
declare module 'wd/lib/commands.js' {
  declare module.exports: $Exports<'wd/lib/commands'>;
}
declare module 'wd/lib/config.js' {
  declare module.exports: $Exports<'wd/lib/config'>;
}
declare module 'wd/lib/deprecated-chain.js' {
  declare module.exports: $Exports<'wd/lib/deprecated-chain'>;
}
declare module 'wd/lib/element-commands.js' {
  declare module.exports: $Exports<'wd/lib/element-commands'>;
}
declare module 'wd/lib/element.js' {
  declare module.exports: $Exports<'wd/lib/element'>;
}
declare module 'wd/lib/http-utils.js' {
  declare module.exports: $Exports<'wd/lib/http-utils'>;
}
declare module 'wd/lib/jsonwire-errors.js' {
  declare module.exports: $Exports<'wd/lib/jsonwire-errors'>;
}
declare module 'wd/lib/lodash.js' {
  declare module.exports: $Exports<'wd/lib/lodash'>;
}
declare module 'wd/lib/main.js' {
  declare module.exports: $Exports<'wd/lib/main'>;
}
declare module 'wd/lib/promise-webdriver.js' {
  declare module.exports: $Exports<'wd/lib/promise-webdriver'>;
}
declare module 'wd/lib/special-keys.js' {
  declare module.exports: $Exports<'wd/lib/special-keys'>;
}
declare module 'wd/lib/tmp.js' {
  declare module.exports: $Exports<'wd/lib/tmp'>;
}
declare module 'wd/lib/utils.js' {
  declare module.exports: $Exports<'wd/lib/utils'>;
}
declare module 'wd/lib/webdriver.js' {
  declare module.exports: $Exports<'wd/lib/webdriver'>;
}
declare module 'wd/scripts/build-browser-scripts.js' {
  declare module.exports: $Exports<'wd/scripts/build-browser-scripts'>;
}
declare module 'wd/test/coverage/run_tests.js' {
  declare module.exports: $Exports<'wd/test/coverage/run_tests'>;
}
declare module 'wd/test/e2e/async.js' {
  declare module.exports: $Exports<'wd/test/e2e/async'>;
}
declare module 'wd/test/e2e/basic-specs.js' {
  declare module.exports: $Exports<'wd/test/e2e/basic-specs'>;
}
declare module 'wd/test/e2e/deprecated-chain-specs.js' {
  declare module.exports: $Exports<'wd/test/e2e/deprecated-chain-specs'>;
}
declare module 'wd/test/e2e/promise-chain-specs.js' {
  declare module.exports: $Exports<'wd/test/e2e/promise-chain-specs'>;
}
declare module 'wd/test/e2e/promise-no-chain-specs.js' {
  declare module.exports: $Exports<'wd/test/e2e/promise-no-chain-specs'>;
}
declare module 'wd/test/e2e/sauce-helpers-specs.js' {
  declare module.exports: $Exports<'wd/test/e2e/sauce-helpers-specs'>;
}
declare module 'wd/test/helpers/env.js' {
  declare module.exports: $Exports<'wd/test/helpers/env'>;
}
declare module 'wd/test/helpers/express-helper.js' {
  declare module.exports: $Exports<'wd/test/helpers/express-helper'>;
}
declare module 'wd/test/helpers/make-tool.js' {
  declare module.exports: $Exports<'wd/test/helpers/make-tool'>;
}
declare module 'wd/test/helpers/mobile_env.js' {
  declare module.exports: $Exports<'wd/test/helpers/mobile_env'>;
}
declare module 'wd/test/helpers/quit-gracefully.js' {
  declare module.exports: $Exports<'wd/test/helpers/quit-gracefully'>;
}
declare module 'wd/test/helpers/setup.js' {
  declare module.exports: $Exports<'wd/test/helpers/setup'>;
}
declare module 'wd/test/helpers/skip.js' {
  declare module.exports: $Exports<'wd/test/helpers/skip'>;
}
declare module 'wd/test/midway/add-methods-async-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/add-methods-async-specs'>;
}
declare module 'wd/test/midway/add-methods-pc-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/add-methods-pc-specs'>;
}
declare module 'wd/test/midway/add-methods-pnc-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/add-methods-pnc-specs'>;
}
declare module 'wd/test/midway/api-el-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/api-el-specs'>;
}
declare module 'wd/test/midway/api-el-suffix-base.js' {
  declare module.exports: $Exports<'wd/test/midway/api-el-suffix-base'>;
}
declare module 'wd/test/midway/api-exec-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/api-exec-specs'>;
}
declare module 'wd/test/midway/api-nav-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/api-nav-specs'>;
}
declare module 'wd/test/midway/api-various-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/api-various-specs'>;
}
declare module 'wd/test/midway/asserters-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/asserters-specs'>;
}
declare module 'wd/test/midway/attach-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/attach-specs'>;
}
declare module 'wd/test/midway/chaining-scope-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/chaining-scope-specs'>;
}
declare module 'wd/test/midway/chaining-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/chaining-specs'>;
}
declare module 'wd/test/midway/element-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/element-specs'>;
}
declare module 'wd/test/midway/external-promises-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/external-promises-specs'>;
}
declare module 'wd/test/midway/frame-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/frame-specs'>;
}
declare module 'wd/test/midway/keying-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/keying-specs'>;
}
declare module 'wd/test/midway/midway-base.js' {
  declare module.exports: $Exports<'wd/test/midway/midway-base'>;
}
declare module 'wd/test/midway/mobile-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/mobile-specs'>;
}
declare module 'wd/test/midway/multi/config-http-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/multi/config-http-specs'>;
}
declare module 'wd/test/midway/multi/init-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/multi/init-specs'>;
}
declare module 'wd/test/midway/multi/status-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/multi/status-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-class-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-class-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-css-sel-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-css-sel-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-css-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-css-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-id-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-id-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-link-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-link-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-name-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-name-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-partial-link-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-partial-link-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-tag-name-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-tag-name-specs'>;
}
declare module 'wd/test/midway/suffixes/api-el-by-xpath-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/suffixes/api-el-by-xpath-specs'>;
}
declare module 'wd/test/midway/typing-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/typing-specs'>;
}
declare module 'wd/test/midway/wait-for-1-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/wait-for-1-specs'>;
}
declare module 'wd/test/midway/wait-for-2-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/wait-for-2-specs'>;
}
declare module 'wd/test/midway/window-specs.js' {
  declare module.exports: $Exports<'wd/test/midway/window-specs'>;
}
declare module 'wd/test/specs/callback-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/callback-specs'>;
}
declare module 'wd/test/specs/http-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/http-specs'>;
}
declare module 'wd/test/specs/init-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/init-specs'>;
}
declare module 'wd/test/specs/mjson-actions-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/mjson-actions-specs'>;
}
declare module 'wd/test/specs/mjson-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/mjson-specs'>;
}
declare module 'wd/test/specs/remote-specs.js' {
  declare module.exports: $Exports<'wd/test/specs/remote-specs'>;
}
