// flow-typed signature: f06df6348c3a29b40125f2299836a8a4
// flow-typed version: <<STUB>>/@react-native-community/art_v^1.2.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/art'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@react-native-community/art" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@react-native-community/art/babel.config" {
  declare module.exports: any;
}

declare module "@react-native-community/art/jest.config" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/__tests__/helpers.test" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/ARTSerializablePath" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/ClippingRectangle" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/Group" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/helpers" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/LinearGradient" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/nativeComponents" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/Pattern" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/RadialGradient" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/Shape" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/Surface" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/Text" {
  declare module.exports: any;
}

declare module "@react-native-community/art/lib/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@react-native-community/art/babel.config.js" {
  declare module.exports: $Exports<"@react-native-community/art/babel.config">;
}
declare module "@react-native-community/art/jest.config.js" {
  declare module.exports: $Exports<"@react-native-community/art/jest.config">;
}
declare module "@react-native-community/art/lib/__tests__/helpers.test.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/__tests__/helpers.test"
  >;
}
declare module "@react-native-community/art/lib/ARTSerializablePath.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/ARTSerializablePath"
  >;
}
declare module "@react-native-community/art/lib/ClippingRectangle.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/ClippingRectangle"
  >;
}
declare module "@react-native-community/art/lib/Group.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/Group">;
}
declare module "@react-native-community/art/lib/helpers.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/helpers">;
}
declare module "@react-native-community/art/lib/index" {
  declare module.exports: $Exports<"@react-native-community/art/lib">;
}
declare module "@react-native-community/art/lib/index.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib">;
}
declare module "@react-native-community/art/lib/LinearGradient.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/LinearGradient"
  >;
}
declare module "@react-native-community/art/lib/nativeComponents.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/nativeComponents"
  >;
}
declare module "@react-native-community/art/lib/Pattern.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/Pattern">;
}
declare module "@react-native-community/art/lib/RadialGradient.js" {
  declare module.exports: $Exports<
    "@react-native-community/art/lib/RadialGradient"
  >;
}
declare module "@react-native-community/art/lib/Shape.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/Shape">;
}
declare module "@react-native-community/art/lib/Surface.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/Surface">;
}
declare module "@react-native-community/art/lib/Text.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/Text">;
}
declare module "@react-native-community/art/lib/types.js" {
  declare module.exports: $Exports<"@react-native-community/art/lib/types">;
}
