// flow-typed signature: a24282cb494fe87f59faf9b10866ffa6
// flow-typed version: <<STUB>>/@react-native-community/async-storage_v^1.5.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/async-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/async-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/async-storage/jest/async-storage-mock' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/AsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/hooks' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/packages/core/build/AsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/packages/core/build/defaults' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/packages/core/build' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/async-storage/jest/async-storage-mock.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/jest/async-storage-mock'>;
}
declare module '@react-native-community/async-storage/lib/AsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/AsyncStorage'>;
}
declare module '@react-native-community/async-storage/lib/hooks.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/hooks'>;
}
declare module '@react-native-community/async-storage/lib/index' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib'>;
}
declare module '@react-native-community/async-storage/lib/index.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib'>;
}
declare module '@react-native-community/async-storage/packages/core/build/AsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/packages/core/build/AsyncStorage'>;
}
declare module '@react-native-community/async-storage/packages/core/build/defaults.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/packages/core/build/defaults'>;
}
declare module '@react-native-community/async-storage/packages/core/build/index' {
  declare module.exports: $Exports<'@react-native-community/async-storage/packages/core/build'>;
}
declare module '@react-native-community/async-storage/packages/core/build/index.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/packages/core/build'>;
}
