// flow-typed signature: 305fd91bf1bdc2f99656d835ec2c820b
// flow-typed version: <<STUB>>/@react-native-community/async-storage_v^1.8.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/async-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@react-native-community/async-storage" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@react-native-community/async-storage/jest/async-storage-mock" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/lib/AsyncStorage" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/lib/hooks" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/lib" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/metro.config" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/metro.config.macos" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/core/build/AsyncStorage" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/core/build/defaults" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/core/build/extension" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/core/build" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/storage-legacy/build" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/packages/storage-web/build" {
  declare module.exports: any;
}

declare module "@react-native-community/async-storage/react-native.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "@react-native-community/async-storage/jest/async-storage-mock.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/jest/async-storage-mock"
  >;
}
declare module "@react-native-community/async-storage/lib/AsyncStorage.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/lib/AsyncStorage"
  >;
}
declare module "@react-native-community/async-storage/lib/hooks.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/lib/hooks"
  >;
}
declare module "@react-native-community/async-storage/lib/index" {
  declare module.exports: $Exports<"@react-native-community/async-storage/lib">;
}
declare module "@react-native-community/async-storage/lib/index.js" {
  declare module.exports: $Exports<"@react-native-community/async-storage/lib">;
}
declare module "@react-native-community/async-storage/metro.config.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/metro.config"
  >;
}
declare module "@react-native-community/async-storage/metro.config.macos.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/metro.config.macos"
  >;
}
declare module "@react-native-community/async-storage/packages/core/build/AsyncStorage.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/core/build/AsyncStorage"
  >;
}
declare module "@react-native-community/async-storage/packages/core/build/defaults.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/core/build/defaults"
  >;
}
declare module "@react-native-community/async-storage/packages/core/build/extension.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/core/build/extension"
  >;
}
declare module "@react-native-community/async-storage/packages/core/build/index" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/core/build"
  >;
}
declare module "@react-native-community/async-storage/packages/core/build/index.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/core/build"
  >;
}
declare module "@react-native-community/async-storage/packages/storage-legacy/build/index" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/storage-legacy/build"
  >;
}
declare module "@react-native-community/async-storage/packages/storage-legacy/build/index.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/storage-legacy/build"
  >;
}
declare module "@react-native-community/async-storage/packages/storage-web/build/index" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/storage-web/build"
  >;
}
declare module "@react-native-community/async-storage/packages/storage-web/build/index.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/packages/storage-web/build"
  >;
}
declare module "@react-native-community/async-storage/react-native.config.js" {
  declare module.exports: $Exports<
    "@react-native-community/async-storage/react-native.config"
  >;
}
