// flow-typed signature: da0c8f5ef0dc5b4689a2bb075d577762
// flow-typed version: <<STUB>>/@react-native-community/hooks_v^2.4.7/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@react-native-community/hooks" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@react-native-community/hooks/lib" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useAccessibilityInfo" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useAppState" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useBackHandler" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useCameraRoll" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useClipboard" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useDeviceOrientation" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useDimensions" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useInteractionManager" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useKeyboard" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useLayout" {
  declare module.exports: any;
}

declare module "@react-native-community/hooks/lib/useLayout.test" {
  declare module.exports: any;
}

// Filename aliases
declare module "@react-native-community/hooks/lib/index" {
  declare module.exports: $Exports<"@react-native-community/hooks/lib">;
}
declare module "@react-native-community/hooks/lib/index.js" {
  declare module.exports: $Exports<"@react-native-community/hooks/lib">;
}
declare module "@react-native-community/hooks/lib/useAccessibilityInfo.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useAccessibilityInfo"
  >;
}
declare module "@react-native-community/hooks/lib/useAppState.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useAppState"
  >;
}
declare module "@react-native-community/hooks/lib/useBackHandler.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useBackHandler"
  >;
}
declare module "@react-native-community/hooks/lib/useCameraRoll.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useCameraRoll"
  >;
}
declare module "@react-native-community/hooks/lib/useClipboard.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useClipboard"
  >;
}
declare module "@react-native-community/hooks/lib/useDeviceOrientation.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useDeviceOrientation"
  >;
}
declare module "@react-native-community/hooks/lib/useDimensions.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useDimensions"
  >;
}
declare module "@react-native-community/hooks/lib/useInteractionManager.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useInteractionManager"
  >;
}
declare module "@react-native-community/hooks/lib/useKeyboard.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useKeyboard"
  >;
}
declare module "@react-native-community/hooks/lib/useLayout.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useLayout"
  >;
}
declare module "@react-native-community/hooks/lib/useLayout.test.js" {
  declare module.exports: $Exports<
    "@react-native-community/hooks/lib/useLayout.test"
  >;
}
