// flow-typed signature: 4a746be11d0ac5bc5f36cb951b0d9f40
// flow-typed version: <<STUB>>/@react-native-community/netinfo_v^5.6.2/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/netinfo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@react-native-community/netinfo" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@react-native-community/netinfo/jest/netinfo-mock" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/internetReachability" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeModule" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeModule.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/privateTypes" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/state" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/commonjs/internal/types" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/defaultConfiguration" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/defaultConfiguration.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/internetReachability" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/nativeInterface" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/nativeInterface.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/nativeModule" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/nativeModule.web" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/privateTypes" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/state" {
  declare module.exports: any;
}

declare module "@react-native-community/netinfo/lib/module/internal/types" {
  declare module.exports: any;
}

// Filename aliases
declare module "@react-native-community/netinfo/jest/netinfo-mock.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/jest/netinfo-mock"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/index" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/index.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/defaultConfiguration.web"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/internetReachability.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/internetReachability"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/nativeInterface.web"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeModule.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/nativeModule"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/nativeModule.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/nativeModule.web"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/privateTypes.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/privateTypes"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/state.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/state"
  >;
}
declare module "@react-native-community/netinfo/lib/commonjs/internal/types.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/commonjs/internal/types"
  >;
}
declare module "@react-native-community/netinfo/lib/module/index" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module"
  >;
}
declare module "@react-native-community/netinfo/lib/module/index.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/defaultConfiguration.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/defaultConfiguration"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/defaultConfiguration.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/defaultConfiguration.web"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/internetReachability.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/internetReachability"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/nativeInterface.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/nativeInterface"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/nativeInterface.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/nativeInterface.web"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/nativeModule.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/nativeModule"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/nativeModule.web.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/nativeModule.web"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/privateTypes.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/privateTypes"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/state.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/state"
  >;
}
declare module "@react-native-community/netinfo/lib/module/internal/types.js" {
  declare module.exports: $Exports<
    "@react-native-community/netinfo/lib/module/internal/types"
  >;
}
