// flow-typed signature: abf4ada13e6d5f98d749a0cc123ad7fc
// flow-typed version: <<STUB>>/@mapbox/geo-viewport_v^0.2.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/geo-viewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/geo-viewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/geo-viewport/example/index' {
  declare module.exports: any;
}

declare module '@mapbox/geo-viewport/geo-viewport' {
  declare module.exports: any;
}

declare module '@mapbox/geo-viewport/test/viewport' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/geo-viewport/example/index.js' {
  declare module.exports: $Exports<'@mapbox/geo-viewport/example/index'>;
}
declare module '@mapbox/geo-viewport/geo-viewport.js' {
  declare module.exports: $Exports<'@mapbox/geo-viewport/geo-viewport'>;
}
declare module '@mapbox/geo-viewport/index' {
  declare module.exports: $Exports<'@mapbox/geo-viewport'>;
}
declare module '@mapbox/geo-viewport/index.js' {
  declare module.exports: $Exports<'@mapbox/geo-viewport'>;
}
declare module '@mapbox/geo-viewport/test/viewport.js' {
  declare module.exports: $Exports<'@mapbox/geo-viewport/test/viewport'>;
}
