// flow-typed signature: 1a3d7021f3f74165e928ad4b7f54fdf6
// flow-typed version: <<STUB>>/@mapbox/react-native-mapbox-gl_v^6.1.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/react-native-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/react-native-mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/react-native-mapbox-gl/javascript/components/AbstractLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/BackgroundLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/Callout' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/CircleLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/FillExtrusionLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/FillLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/ImageSource' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/Light' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/LineLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/MapView' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/PointAnnotation' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/RasterLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/RasterSource' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/ShapeSource' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/SymbolLayer' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/components/VectorSource' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/index' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflineCreatePackOptions' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/offlineManager' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflinePack' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/snapshotManager' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/SnapshotOptions' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/BridgeValue' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/filterUtils' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/geoUtils' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/index' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/MapboxStyleSheet' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/javascript/utils/styleMap' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/autogenerate' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/DocJSONBuilder' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/globals' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/JSDocNodeTree' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/MarkdownBuilder' {
  declare module.exports: any;
}

declare module '@mapbox/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/react-native-mapbox-gl/javascript/components/AbstractLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/AbstractLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/BackgroundLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/BackgroundLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/Callout.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/Callout'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/CircleLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/CircleLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/FillExtrusionLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/FillExtrusionLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/FillLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/FillLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/ImageSource.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/ImageSource'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/Light.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/Light'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/LineLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/LineLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/MapView.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/MapView'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/PointAnnotation.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/PointAnnotation'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/RasterLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/RasterLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/RasterSource.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/RasterSource'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/ShapeSource.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/ShapeSource'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/SymbolLayer.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/SymbolLayer'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/components/VectorSource.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/components/VectorSource'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/index.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/index'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflineCreatePackOptions.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflineCreatePackOptions'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/offlineManager.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/modules/offline/offlineManager'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflinePack.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/modules/offline/OfflinePack'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/snapshotManager.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/snapshotManager'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/SnapshotOptions.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/modules/snapshot/SnapshotOptions'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/BridgeValue.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/BridgeValue'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/filterUtils.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/filterUtils'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/geoUtils.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/geoUtils'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/index.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/index'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/MapboxStyleSheet.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/MapboxStyleSheet'>;
}
declare module '@mapbox/react-native-mapbox-gl/javascript/utils/styleMap.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/javascript/utils/styleMap'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/autogenerate.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/autogenerate'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/DocJSONBuilder.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/DocJSONBuilder'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/globals.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/globals'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/JSDocNodeTree.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/JSDocNodeTree'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/MarkdownBuilder.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/autogenHelpers/MarkdownBuilder'>;
}
declare module '@mapbox/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac.js' {
  declare module.exports: $Exports<'@mapbox/react-native-mapbox-gl/scripts/download-mapbox-gl-native-ios-if-on-mac'>;
}
