// flow-typed signature: 56ba81d09cef539b598429ea544016de
// flow-typed version: <<STUB>>/@unimodules/core_v^0.2.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@unimodules/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@unimodules/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@unimodules/core/index' {
  declare module.exports: $Exports<'@unimodules/core'>;
}
declare module '@unimodules/core/index.js' {
  declare module.exports: $Exports<'@unimodules/core'>;
}
