// flow-typed signature: 236c146a7db484d9282d8b465e1ae39f
// flow-typed version: <<STUB>>/@digidem/wcmc-mapeo-mobile-intro_v^1.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@digidem/wcmc-mapeo-mobile-intro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@digidem/wcmc-mapeo-mobile-intro" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroDots" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroInfo" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroPager" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroScreen" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/Markdown" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/screenDefs" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/UniversalImage" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroDots" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroInfo" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroPager" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroScreen" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/Markdown" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/screenDefs" {
  declare module.exports: any;
}

declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/UniversalImage" {
  declare module.exports: any;
}

// Filename aliases
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/index" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/index.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroDots.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroDots"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroInfo.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroInfo"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroPager.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroPager"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroScreen.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/IntroScreen"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/Markdown.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/Markdown"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/screenDefs.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/screenDefs"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/UniversalImage.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/commonjs/UniversalImage"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/index" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/index.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroDots.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroDots"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroInfo.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroInfo"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroPager.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroPager"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroScreen.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/IntroScreen"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/Markdown.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/Markdown"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/screenDefs.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/screenDefs"
  >;
}
declare module "@digidem/wcmc-mapeo-mobile-intro/lib/module/UniversalImage.js" {
  declare module.exports: $Exports<
    "@digidem/wcmc-mapeo-mobile-intro/lib/module/UniversalImage"
  >;
}
