// flow-typed signature: c895a4e72099278a6cff4e10d1b4f816
// flow-typed version: <<STUB>>/@react-native-mapbox-gl/maps_vreact-native-mapbox-gl/maps#59238cd3c9a21cbc875989d7efcec7ecc7a9db74/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-mapbox-gl/maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-mapbox-gl/maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-mapbox-gl/maps/babel.config' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/AbstractLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/AbstractSource' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/annotations/Annotation' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/BackgroundLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/Callout' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/Camera' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/CircleLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/FillExtrusionLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/FillLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/HeatmapLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/Images' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/ImageSource' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/Light' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/LineLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/MapView' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/NativeBridgeComponent' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/PointAnnotation' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/RasterLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/RasterSource' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/ShapeSource' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/SymbolLayer' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/UserLocation' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/components/VectorSource' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/location/locationManager' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/OfflineCreatePackOptions' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/offlineManager' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/OfflinePack' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/snapshot/snapshotManager' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/modules/snapshot/SnapshotOptions' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils/AnimatedPoint' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils/BridgeValue' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils/filterUtils' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils/geoUtils' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/javascript/utils/styleMap' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/autogenerate' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/DocJSONBuilder' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/globals' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/JSDocNodeTree' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/MarkdownBuilder' {
  declare module.exports: any;
}

declare module '@react-native-mapbox-gl/maps/scripts/download-mapbox-gl-native-ios-if-on-mac' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-mapbox-gl/maps/babel.config.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/babel.config'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/AbstractLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/AbstractLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/AbstractSource.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/AbstractSource'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/annotations/Annotation.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/annotations/Annotation'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/BackgroundLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/BackgroundLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/Callout.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/Callout'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/Camera.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/Camera'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/CircleLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/CircleLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/FillExtrusionLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/FillExtrusionLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/FillLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/FillLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/HeatmapLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/HeatmapLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/Images.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/Images'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/ImageSource.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/ImageSource'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/Light.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/Light'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/LineLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/LineLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/MapView.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/MapView'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/NativeBridgeComponent.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/NativeBridgeComponent'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/PointAnnotation.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/PointAnnotation'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/RasterLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/RasterLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/RasterSource.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/RasterSource'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/ShapeSource.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/ShapeSource'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/SymbolLayer.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/SymbolLayer'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/UserLocation.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/UserLocation'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/components/VectorSource.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/components/VectorSource'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/index' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/index.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/location/locationManager.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/location/locationManager'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/OfflineCreatePackOptions.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/offline/OfflineCreatePackOptions'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/offlineManager.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/offline/offlineManager'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/offline/OfflinePack.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/offline/OfflinePack'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/snapshot/snapshotManager.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/snapshot/snapshotManager'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/modules/snapshot/SnapshotOptions.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/modules/snapshot/SnapshotOptions'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/AnimatedPoint.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils/AnimatedPoint'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/BridgeValue.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils/BridgeValue'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/filterUtils.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils/filterUtils'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/geoUtils.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils/geoUtils'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/index' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/index.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils'>;
}
declare module '@react-native-mapbox-gl/maps/javascript/utils/styleMap.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/javascript/utils/styleMap'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/autogenerate.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/autogenerate'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/DocJSONBuilder.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/autogenHelpers/DocJSONBuilder'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/globals.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/autogenHelpers/globals'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/JSDocNodeTree.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/autogenHelpers/JSDocNodeTree'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/autogenHelpers/MarkdownBuilder.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/autogenHelpers/MarkdownBuilder'>;
}
declare module '@react-native-mapbox-gl/maps/scripts/download-mapbox-gl-native-ios-if-on-mac.js' {
  declare module.exports: $Exports<'@react-native-mapbox-gl/maps/scripts/download-mapbox-gl-native-ios-if-on-mac'>;
}
